<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sqlInsert = "INSERT INTO `countries` (`id`, `iso_2`, `iso_3`, `name`, `capital`, `area`, `flag`, `currency_code`, `currency_symbol`)
VALUES
	(1,'AD','','Andorra',NULL,NULL,NULL,NULL,NULL),
	(2,'AF','','Afghanistan',NULL,NULL,NULL,NULL,NULL),
	(3,'AX','','Åland Islands',NULL,NULL,NULL,NULL,NULL),
	(4,'AL','','Albania',NULL,NULL,NULL,NULL,NULL),
	(5,'DZ','','Algeria',NULL,NULL,NULL,NULL,NULL),
	(6,'AS','','American Samoa',NULL,NULL,NULL,NULL,NULL),
	(7,'AO','','Angola',NULL,NULL,NULL,NULL,NULL),
	(8,'AI','','Anguilla',NULL,NULL,NULL,NULL,NULL),
	(9,'AQ','','Antarctica',NULL,NULL,NULL,NULL,NULL),
	(10,'AG','','Antigua and Barbuda',NULL,NULL,NULL,NULL,NULL),
	(11,'AR','','Argentina',NULL,NULL,NULL,NULL,NULL),
	(12,'AM','','Armenia',NULL,NULL,NULL,NULL,NULL),
	(13,'AW','','Aruba',NULL,NULL,NULL,NULL,NULL),
	(14,'AU','','Australia',NULL,NULL,NULL,NULL,NULL),
	(15,'AT','','Austria',NULL,NULL,NULL,NULL,NULL),
	(16,'AZ','','Azerbaijan',NULL,NULL,NULL,NULL,NULL),
	(17,'BS','','Bahamas',NULL,NULL,NULL,NULL,NULL),
	(18,'BH','','Bahrain',NULL,NULL,NULL,NULL,NULL),
	(19,'BD','','Bangladesh',NULL,NULL,NULL,NULL,NULL),
	(20,'BB','','Barbados',NULL,NULL,NULL,NULL,NULL),
	(21,'BY','','Belarus',NULL,NULL,NULL,NULL,NULL),
	(22,'BE','','Belgium',NULL,NULL,NULL,NULL,NULL),
	(23,'BZ','','Belize',NULL,NULL,NULL,NULL,NULL),
	(24,'BJ','','Benin',NULL,NULL,NULL,NULL,NULL),
	(25,'BM','','Bermuda',NULL,NULL,NULL,NULL,NULL),
	(26,'BT','','Bhutan',NULL,NULL,NULL,NULL,NULL),
	(27,'BO','','Bolivia (Plurinational State of)',NULL,NULL,NULL,NULL,NULL),
	(28,'BQ','','Bonaire, Sint Eustatius and Saba',NULL,NULL,NULL,NULL,NULL),
	(29,'BA','','Bosnia and Herzegovina',NULL,NULL,NULL,NULL,NULL),
	(30,'BW','','Botswana',NULL,NULL,NULL,NULL,NULL),
	(31,'BV','','Bouvet Island',NULL,NULL,NULL,NULL,NULL),
	(32,'BR','','Brazil',NULL,NULL,NULL,NULL,NULL),
	(33,'IO','','British Indian Ocean Territory',NULL,NULL,NULL,NULL,NULL),
	(34,'BN','','Brunei Darussalam',NULL,NULL,NULL,NULL,NULL),
	(35,'BG','','Bulgaria',NULL,NULL,NULL,NULL,NULL),
	(36,'BF','','Burkina Faso',NULL,NULL,NULL,NULL,NULL),
	(37,'BI','','Burundi',NULL,NULL,NULL,NULL,NULL),
	(38,'CV','','Cabo Verde',NULL,NULL,NULL,NULL,NULL),
	(39,'KH','','Cambodia',NULL,NULL,NULL,NULL,NULL),
	(40,'CM','','Cameroon',NULL,NULL,NULL,NULL,NULL),
	(41,'CA','','Canada',NULL,NULL,NULL,NULL,NULL),
	(42,'KY','','Cayman Islands',NULL,NULL,NULL,NULL,NULL),
	(43,'CF','','Central African Republic',NULL,NULL,NULL,NULL,NULL),
	(44,'TD','','Chad',NULL,NULL,NULL,NULL,NULL),
	(45,'CL','','Chile',NULL,NULL,NULL,NULL,NULL),
	(46,'CN','','China',NULL,NULL,NULL,NULL,NULL),
	(47,'CX','','Christmas Island',NULL,NULL,NULL,NULL,NULL),
	(48,'CC','','Cocos (Keeling) Islands',NULL,NULL,NULL,NULL,NULL),
	(49,'CO','','Colombia',NULL,NULL,NULL,NULL,NULL),
	(50,'KM','','Comoros',NULL,NULL,NULL,NULL,NULL),
	(51,'CG','','Congo',NULL,NULL,NULL,NULL,NULL),
	(52,'CD','','Congo (Democratic Republic of the)',NULL,NULL,NULL,NULL,NULL),
	(53,'CK','','Cook Islands',NULL,NULL,NULL,NULL,NULL),
	(54,'CR','','Costa Rica',NULL,NULL,NULL,NULL,NULL),
	(55,'CI','','Côte d\'Ivoire',NULL,NULL,NULL,NULL,NULL),
	(56,'HR','','Croatia',NULL,NULL,NULL,NULL,NULL),
	(57,'CU','','Cuba',NULL,NULL,NULL,NULL,NULL),
	(58,'CW','','Curaçao',NULL,NULL,NULL,NULL,NULL),
	(59,'CY','','Cyprus',NULL,NULL,NULL,NULL,NULL),
	(60,'CZ','','Czech Republic',NULL,NULL,NULL,NULL,NULL),
	(61,'DK','','Denmark',NULL,NULL,NULL,NULL,NULL),
	(62,'DJ','','Djibouti',NULL,NULL,NULL,NULL,NULL),
	(63,'DM','','Dominica',NULL,NULL,NULL,NULL,NULL),
	(64,'DO','','Dominican Republic',NULL,NULL,NULL,NULL,NULL),
	(65,'EC','','Ecuador',NULL,NULL,NULL,NULL,NULL),
	(66,'EG','','Egypt',NULL,NULL,NULL,NULL,NULL),
	(67,'SV','','El Salvador',NULL,NULL,NULL,NULL,NULL),
	(68,'GQ','','Equatorial Guinea',NULL,NULL,NULL,NULL,NULL),
	(69,'ER','','Eritrea',NULL,NULL,NULL,NULL,NULL),
	(70,'EE','','Estonia',NULL,NULL,NULL,NULL,NULL),
	(71,'ET','','Ethiopia',NULL,NULL,NULL,NULL,NULL),
	(72,'FK','','Falkland Islands (Malvinas)',NULL,NULL,NULL,NULL,NULL),
	(73,'FO','','Faroe Islands',NULL,NULL,NULL,NULL,NULL),
	(74,'FJ','','Fiji',NULL,NULL,NULL,NULL,NULL),
	(75,'FI','','Finland',NULL,NULL,NULL,NULL,NULL),
	(76,'FR','','France',NULL,NULL,NULL,NULL,NULL),
	(77,'GF','','French Guiana',NULL,NULL,NULL,NULL,NULL),
	(78,'PF','','French Polynesia',NULL,NULL,NULL,NULL,NULL),
	(79,'TF','','French Southern Territories',NULL,NULL,NULL,NULL,NULL),
	(80,'GA','','Gabon',NULL,NULL,NULL,NULL,NULL),
	(81,'GM','','Gambia',NULL,NULL,NULL,NULL,NULL),
	(82,'GE','','Georgia',NULL,NULL,NULL,NULL,NULL),
	(83,'DE','','Germany',NULL,NULL,NULL,NULL,NULL),
	(84,'GH','','Ghana',NULL,NULL,NULL,NULL,NULL),
	(85,'GI','','Gibraltar',NULL,NULL,NULL,NULL,NULL),
	(86,'GR','','Greece',NULL,NULL,NULL,NULL,NULL),
	(87,'GL','','Greenland',NULL,NULL,NULL,NULL,NULL),
	(88,'GD','','Grenada',NULL,NULL,NULL,NULL,NULL),
	(89,'GP','','Guadeloupe',NULL,NULL,NULL,NULL,NULL),
	(90,'GU','','Guam',NULL,NULL,NULL,NULL,NULL),
	(91,'GT','','Guatemala',NULL,NULL,NULL,NULL,NULL),
	(92,'GG','','Guernsey',NULL,NULL,NULL,NULL,NULL),
	(93,'GN','','Guinea',NULL,NULL,NULL,NULL,NULL),
	(94,'GW','','Guinea-Bissau',NULL,NULL,NULL,NULL,NULL),
	(95,'GY','','Guyana',NULL,NULL,NULL,NULL,NULL),
	(96,'HT','','Haiti',NULL,NULL,NULL,NULL,NULL),
	(97,'HM','','Heard Island and McDonald Islands',NULL,NULL,NULL,NULL,NULL),
	(98,'VA','','Holy See',NULL,NULL,NULL,NULL,NULL),
	(99,'HN','','Honduras',NULL,NULL,NULL,NULL,NULL),
	(100,'HK','','Hong Kong',NULL,NULL,NULL,NULL,NULL),
	(101,'HU','','Hungary',NULL,NULL,NULL,NULL,NULL),
	(102,'IS','','Iceland',NULL,NULL,NULL,NULL,NULL),
	(103,'IN','','India',NULL,NULL,NULL,NULL,NULL),
	(104,'ID','','Indonesia',NULL,NULL,NULL,NULL,NULL),
	(105,'IR','','Iran (Islamic Republic of)',NULL,NULL,NULL,NULL,NULL),
	(106,'IQ','','Iraq',NULL,NULL,NULL,NULL,NULL),
	(107,'IE','','Ireland',NULL,NULL,NULL,NULL,NULL),
	(108,'IM','','Isle of Man',NULL,NULL,NULL,NULL,NULL),
	(109,'IL','','Israel',NULL,NULL,NULL,NULL,NULL),
	(110,'IT','','Italy',NULL,NULL,NULL,NULL,NULL),
	(111,'JM','','Jamaica',NULL,NULL,NULL,NULL,NULL),
	(112,'JP','','Japan',NULL,NULL,NULL,NULL,NULL),
	(113,'JE','','Jersey',NULL,NULL,NULL,NULL,NULL),
	(114,'JO','','Jordan',NULL,NULL,NULL,NULL,NULL),
	(115,'KZ','','Kazakhstan',NULL,NULL,NULL,NULL,NULL),
	(116,'KE','','Kenya',NULL,NULL,NULL,NULL,NULL),
	(117,'KI','','Kiribati',NULL,NULL,NULL,NULL,NULL),
	(118,'KP','','Korea (Democratic People\'s Republic of)',NULL,NULL,NULL,NULL,NULL),
	(119,'KR','','Korea (Republic of)',NULL,NULL,NULL,NULL,NULL),
	(120,'KW','','Kuwait',NULL,NULL,NULL,NULL,NULL),
	(121,'KG','','Kyrgyzstan',NULL,NULL,NULL,NULL,NULL),
	(122,'LA','','Lao People\'s Democratic Republic',NULL,NULL,NULL,NULL,NULL),
	(123,'LV','','Latvia',NULL,NULL,NULL,NULL,NULL),
	(124,'LB','','Lebanon',NULL,NULL,NULL,NULL,NULL),
	(125,'LS','','Lesotho',NULL,NULL,NULL,NULL,NULL),
	(126,'LR','','Liberia',NULL,NULL,NULL,NULL,NULL),
	(127,'LY','','Libya',NULL,NULL,NULL,NULL,NULL),
	(128,'LI','','Liechtenstein',NULL,NULL,NULL,NULL,NULL),
	(129,'LT','','Lithuania',NULL,NULL,NULL,NULL,NULL),
	(130,'LU','','Luxembourg',NULL,NULL,NULL,NULL,NULL),
	(131,'MO','','Macao',NULL,NULL,NULL,NULL,NULL),
	(132,'MK','','Macedonia (the former Yugoslav Republic of)',NULL,NULL,NULL,NULL,NULL),
	(133,'MG','','Madagascar',NULL,NULL,NULL,NULL,NULL),
	(134,'MW','','Malawi',NULL,NULL,NULL,NULL,NULL),
	(135,'MY','','Malaysia',NULL,NULL,NULL,NULL,NULL),
	(136,'MV','','Maldives',NULL,NULL,NULL,NULL,NULL),
	(137,'ML','','Mali',NULL,NULL,NULL,NULL,NULL),
	(138,'MT','','Malta',NULL,NULL,NULL,NULL,NULL),
	(139,'MH','','Marshall Islands',NULL,NULL,NULL,NULL,NULL),
	(140,'MQ','','Martinique',NULL,NULL,NULL,NULL,NULL),
	(141,'MR','','Mauritania',NULL,NULL,NULL,NULL,NULL),
	(142,'MU','','Mauritius',NULL,NULL,NULL,NULL,NULL),
	(143,'YT','','Mayotte',NULL,NULL,NULL,NULL,NULL),
	(144,'MX','','Mexico',NULL,NULL,NULL,NULL,NULL),
	(145,'FM','','Micronesia (Federated States of)',NULL,NULL,NULL,NULL,NULL),
	(146,'MD','','Moldova (Republic of)',NULL,NULL,NULL,NULL,NULL),
	(147,'MC','','Monaco',NULL,NULL,NULL,NULL,NULL),
	(148,'MN','','Mongolia',NULL,NULL,NULL,NULL,NULL),
	(149,'ME','','Montenegro',NULL,NULL,NULL,NULL,NULL),
	(150,'MS','','Montserrat',NULL,NULL,NULL,NULL,NULL),
	(151,'MA','','Morocco',NULL,NULL,NULL,NULL,NULL),
	(152,'MZ','','Mozambique',NULL,NULL,NULL,NULL,NULL),
	(153,'MM','','Myanmar',NULL,NULL,NULL,NULL,NULL),
	(154,'NA','','Namibia',NULL,NULL,NULL,NULL,NULL),
	(155,'NR','','Nauru',NULL,NULL,NULL,NULL,NULL),
	(156,'NP','','Nepal',NULL,NULL,NULL,NULL,NULL),
	(157,'NL','','Netherlands',NULL,NULL,NULL,NULL,NULL),
	(158,'NC','','New Caledonia',NULL,NULL,NULL,NULL,NULL),
	(159,'NZ','','New Zealand',NULL,NULL,NULL,NULL,NULL),
	(160,'NI','','Nicaragua',NULL,NULL,NULL,NULL,NULL),
	(161,'NE','','Niger',NULL,NULL,NULL,NULL,NULL),
	(162,'NG','','Nigeria',NULL,NULL,NULL,NULL,NULL),
	(163,'NU','','Niue',NULL,NULL,NULL,NULL,NULL),
	(164,'NF','','Norfolk Island',NULL,NULL,NULL,NULL,NULL),
	(165,'MP','','Northern Mariana Islands',NULL,NULL,NULL,NULL,NULL),
	(166,'NO','','Norway',NULL,NULL,NULL,NULL,NULL),
	(167,'OM','','Oman',NULL,NULL,NULL,NULL,NULL),
	(168,'PK','','Pakistan',NULL,NULL,NULL,NULL,NULL),
	(169,'PW','','Palau',NULL,NULL,NULL,NULL,NULL),
	(170,'PS','','Palestine, State of',NULL,NULL,NULL,NULL,NULL),
	(171,'PA','','Panama',NULL,NULL,NULL,NULL,NULL),
	(172,'PG','','Papua New Guinea',NULL,NULL,NULL,NULL,NULL),
	(173,'PY','','Paraguay',NULL,NULL,NULL,NULL,NULL),
	(174,'PE','','Peru',NULL,NULL,NULL,NULL,NULL),
	(175,'PH','','Philippines',NULL,NULL,NULL,NULL,NULL),
	(176,'PN','','Pitcairn',NULL,NULL,NULL,NULL,NULL),
	(177,'PL','','Poland',NULL,NULL,NULL,NULL,NULL),
	(178,'PT','','Portugal',NULL,NULL,NULL,NULL,NULL),
	(179,'PR','','Puerto Rico',NULL,NULL,NULL,NULL,NULL),
	(180,'QA','','Qatar',NULL,NULL,NULL,NULL,NULL),
	(181,'RE','','Réunion',NULL,NULL,NULL,NULL,NULL),
	(182,'RO','','Romania',NULL,NULL,NULL,NULL,NULL),
	(183,'RU','','Russian Federation',NULL,NULL,NULL,NULL,NULL),
	(184,'RW','','Rwanda',NULL,NULL,NULL,NULL,NULL),
	(185,'BL','','Saint Barthélemy',NULL,NULL,NULL,NULL,NULL),
	(186,'SH','','Saint Helena, Ascension and Tristan da Cunha',NULL,NULL,NULL,NULL,NULL),
	(187,'KN','','Saint Kitts and Nevis',NULL,NULL,NULL,NULL,NULL),
	(188,'LC','','Saint Lucia',NULL,NULL,NULL,NULL,NULL),
	(189,'MF','','Saint Martin (French part)',NULL,NULL,NULL,NULL,NULL),
	(190,'PM','','Saint Pierre and Miquelon',NULL,NULL,NULL,NULL,NULL),
	(191,'VC','','Saint Vincent and the Grenadines',NULL,NULL,NULL,NULL,NULL),
	(192,'WS','','Samoa',NULL,NULL,NULL,NULL,NULL),
	(193,'SM','','San Marino',NULL,NULL,NULL,NULL,NULL),
	(194,'ST','','Sao Tome and Principe',NULL,NULL,NULL,NULL,NULL),
	(195,'SA','','Saudi Arabia',NULL,NULL,NULL,NULL,NULL),
	(196,'SN','','Senegal',NULL,NULL,NULL,NULL,NULL),
	(197,'RS','','Serbia',NULL,NULL,NULL,NULL,NULL),
	(198,'SC','','Seychelles',NULL,NULL,NULL,NULL,NULL),
	(199,'SL','','Sierra Leone',NULL,NULL,NULL,NULL,NULL),
	(200,'SG','','Singapore',NULL,NULL,NULL,NULL,NULL),
	(201,'SX','','Sint Maarten (Dutch part)',NULL,NULL,NULL,NULL,NULL),
	(202,'SK','','Slovakia',NULL,NULL,NULL,NULL,NULL),
	(203,'SI','','Slovenia',NULL,NULL,NULL,NULL,NULL),
	(204,'SB','','Solomon Islands',NULL,NULL,NULL,NULL,NULL),
	(205,'SO','','Somalia',NULL,NULL,NULL,NULL,NULL),
	(206,'ZA','','South Africa',NULL,NULL,NULL,NULL,NULL),
	(207,'GS','','South Georgia and the South Sandwich Islands',NULL,NULL,NULL,NULL,NULL),
	(208,'SS','','South Sudan',NULL,NULL,NULL,NULL,NULL),
	(209,'ES','','Spain',NULL,NULL,NULL,NULL,NULL),
	(210,'LK','','Sri Lanka',NULL,NULL,NULL,NULL,NULL),
	(211,'SD','','Sudan',NULL,NULL,NULL,NULL,NULL),
	(212,'SR','','Suriname',NULL,NULL,NULL,NULL,NULL),
	(213,'SJ','','Svalbard and Jan Mayen',NULL,NULL,NULL,NULL,NULL),
	(214,'SZ','','Swaziland',NULL,NULL,NULL,NULL,NULL),
	(215,'SE','','Sweden',NULL,NULL,NULL,NULL,NULL),
	(216,'CH','','Switzerland',NULL,NULL,NULL,NULL,NULL),
	(217,'SY','','Syrian Arab Republic',NULL,NULL,NULL,NULL,NULL),
	(218,'TW','','Taiwan, Province of China',NULL,NULL,NULL,NULL,NULL),
	(219,'TJ','','Tajikistan',NULL,NULL,NULL,NULL,NULL),
	(220,'TZ','','Tanzania, United Republic of',NULL,NULL,NULL,NULL,NULL),
	(221,'TH','','Thailand',NULL,NULL,NULL,NULL,NULL),
	(222,'TL','','Timor-Leste',NULL,NULL,NULL,NULL,NULL),
	(223,'TG','','Togo',NULL,NULL,NULL,NULL,NULL),
	(224,'TK','','Tokelau',NULL,NULL,NULL,NULL,NULL),
	(225,'TO','','Tonga',NULL,NULL,NULL,NULL,NULL),
	(226,'TT','','Trinidad and Tobago',NULL,NULL,NULL,NULL,NULL),
	(227,'TN','','Tunisia',NULL,NULL,NULL,NULL,NULL),
	(228,'TR','','Turkey',NULL,NULL,NULL,NULL,NULL),
	(229,'TM','','Turkmenistan',NULL,NULL,NULL,NULL,NULL),
	(230,'TC','','Turks and Caicos Islands',NULL,NULL,NULL,NULL,NULL),
	(231,'TV','','Tuvalu',NULL,NULL,NULL,NULL,NULL),
	(232,'UG','','Uganda',NULL,NULL,NULL,NULL,NULL),
	(233,'UA','','Ukraine',NULL,NULL,NULL,NULL,NULL),
	(234,'AE','','United Arab Emirates',NULL,NULL,NULL,NULL,NULL),
	(235,'GB','','United Kingdom',NULL,NULL,NULL,NULL,NULL),
	(236,'UM','','United States Minor Outlying Islands',NULL,NULL,NULL,NULL,NULL),
	(237,'US','','United States of America',NULL,NULL,NULL,NULL,NULL),
	(238,'UY','','Uruguay',NULL,NULL,NULL,NULL,NULL),
	(239,'UZ','','Uzbekistan',NULL,NULL,NULL,NULL,NULL),
	(240,'VU','','Vanuatu',NULL,NULL,NULL,NULL,NULL),
	(241,'VE','','Venezuela (Bolivarian Republic of)',NULL,NULL,NULL,NULL,NULL),
	(242,'VN','','Viet Nam',NULL,NULL,NULL,NULL,NULL),
	(243,'VG','','Virgin Islands (British)',NULL,NULL,NULL,NULL,NULL),
	(244,'VI','','Virgin Islands (U.S.)',NULL,NULL,NULL,NULL,NULL),
	(245,'WF','','Wallis and Futuna',NULL,NULL,NULL,NULL,NULL),
	(246,'EH','','Western Sahara',NULL,NULL,NULL,NULL,NULL),
	(247,'YE','','Yemen',NULL,NULL,NULL,NULL,NULL),
	(248,'ZM','','Zambia',NULL,NULL,NULL,NULL,NULL),
	(249,'ZW','','Zimbabwe',NULL,NULL,NULL,NULL,NULL),
	(250,'AN','','Netherland Antilles',NULL,NULL,NULL,NULL,NULL),
	(251,'AC','','Ascension Island',NULL,NULL,NULL,NULL,NULL),
	(252,'TA','','Tristan da Cunha',NULL,NULL,NULL,NULL,NULL),
	(253,'KV','','Kosovo',NULL,NULL,NULL,NULL,NULL),
	(254,'IC','','Canary Islands',NULL,NULL,NULL,NULL,NULL);";

        DB::statement($sqlInsert);
    }
}
